# -*- coding: utf-8 -*-
"""Task 1: Credit Scoring Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Nc0udsUmUvBq3DHTwsqruFAnY8P3lY6

CodeAlpha Machine Learning Internship
Task 1: Credit Scoring Model

Approach:
 - Build a synthetic but realistic financial dataset.
 - Preprocess data (scaling, train/test split).
 - Train and compare 3 classifiers: Logistic Regression, Decision Tree,
   and Random Forest.
 - Evaluate using Accuracy, Precision, Recall, F1-score, and ROC-AUC.

Author: (Nusrat Jahan)
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, classification_report, confusion_matrix
)

np.random.seed(42)
n_samples = 2000

age = np.random.randint(21, 65, n_samples)
annual_income = np.random.normal(45000, 15000, n_samples).clip(10000, 150000)
existing_loans = np.random.poisson(1.2, n_samples)
loan_amount = np.random.normal(15000, 8000, n_samples).clip(500, 60000)
debt_to_income = (existing_loans * loan_amount) / (annual_income + 1)
late_payments_last_year = np.random.poisson(0.8, n_samples)
credit_history_years = np.random.randint(0, 30, n_samples)
employment_years = np.random.randint(0, 35, n_samples)

score = (
    -2.5 * debt_to_income
    - 0.8 * late_payments_last_year
    + 0.05 * credit_history_years
    + 0.02 * employment_years
    + 0.00002 * annual_income
    + np.random.normal(0, 0.5, n_samples)
)
creditworthy = (score > np.median(score)).astype(int)

df = pd.DataFrame({
    "age": age,
    "annual_income": annual_income.round(2),
    "existing_loans": existing_loans,
    "loan_amount": loan_amount.round(2),
    "debt_to_income": debt_to_income.round(4),
    "late_payments_last_year": late_payments_last_year,
    "credit_history_years": credit_history_years,
    "employment_years": employment_years,
    "creditworthy": creditworthy
})

print("Sample of the dataset:")
print(df.head())
print("\nClass balance:")
print(df["creditworthy"].value_counts())

df.to_csv("credit_scoring_dataset.csv", index=False)

X = df.drop("creditworthy", axis=1)
y = df["creditworthy"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42)
}

results = []

for name, model in models.items():
    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_proba)

    results.append([name, acc, prec, rec, f1, roc])

    print(f"\n {name} ")
    print(classification_report(y_test, y_pred, target_names=["Not Creditworthy", "Creditworthy"]))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print(f"ROC-AUC: {roc:.4f}")

results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"])
print("\nFinal Comparison ")
print(results_df.to_string(index=False))

results_df.to_csv("task1_model_comparison.csv", index=False)

rf = models["Random Forest"]
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nFeature importance (Random Forest):")
print(importances)

print(df.head())
print(df.columns)

import joblib
import matplotlib.pyplot as plt

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    GridSearchCV
)

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    RocCurveDisplay
)

df["income_per_loan"] = (
    df["annual_income"] /
    (df["existing_loans"] + 1)
)

df["late_payment_ratio"] = (
    df["late_payments_last_year"] /
    (df["credit_history_years"] + 1)
)

df["employment_stability"] = (
    df["employment_years"] /
    (df["age"] + 1)
)

print('Re-generating data splits and scaling with new features...')
X = df.drop("creditworthy", axis=1)
y = df["creditworthy"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print('Data splits and scaling updated.')

print('Re-training models with updated feature set...')
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(max_depth=5, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42)
}

results = []

for name, model in models.items():
    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_proba)

    results.append([name, acc, prec, rec, f1, roc])

    print(f"\n {name} ")
    print(classification_report(y_test, y_pred, target_names=["Not Creditworthy", "Creditworthy"]))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print(f"ROC-AUC: {roc:.4f}")

results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"])
print("\nFinal Comparison ")
print(results_df.to_string(index=False))

results_df.to_csv("task1_model_comparison.csv", index=False)

lr = models["Logistic Regression"]
dt = models["Decision Tree"]
rf = models["Random Forest"]
print('Models re-trained.')

print('Explicitly re-training Logistic Regression model...')
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)
print('Logistic Regression model re-trained.')

print('Plotting ROC curves...')
plt.figure(figsize=(8,6))

RocCurveDisplay.from_estimator(
    lr,
    X_test_scaled,
    y_test
)

RocCurveDisplay.from_estimator(
    dt,
    X_test,
    y_test
)

RocCurveDisplay.from_estimator(
    rf,
    X_test,
    y_test
)

plt.title("ROC Curve Comparison")
plt.show()
print('ROC curves displayed.')

"""Cross Validation"""

cv_scores = cross_val_score(
    rf,
    X_train,
    y_train,
    cv=5,
    scoring="f1"
)

print("\nCross Validation F1 Scores:")
print(cv_scores)

print(
    "\nMean CV F1 Score:",
    cv_scores.mean()
)

print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of X_test_scaled: {X_test_scaled.shape}")

""" Feature Importance"""

feature_importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
).sort_values()

plt.figure(figsize=(10,6))

feature_importance.plot(
    kind="barh"
)

plt.title(
    "Random Forest Feature Importance"
)

plt.tight_layout()

plt.show()

print("\nFeature Importance:")
print(
    feature_importance.sort_values(
        ascending=False
    )
)

"""Save Model and Scaler"""

joblib.dump(
    rf,
    "best_credit_scoring_model.pkl"
)

joblib.dump(
    scaler,
    "credit_scaler.pkl"
)

print(
    "\nModel saved successfully."
)

"""Business Insights"""

print("\nBusiness Insights")

top_features = feature_importance.sort_values(
    ascending=False
).head(5)

print(
    "\nTop 5 Important Features:"
)

print(top_features)